/*
 Navicat Premium Data Transfer

 Source Server         : Local
 Source Server Type    : MySQL
 Source Server Version : 80030 (8.0.30)
 Source Host           : localhost:3306
 Source Schema         : book

 Target Server Type    : MySQL
 Target Server Version : 80030 (8.0.30)
 File Encoding         : 65001

 Date: 08/12/2022 10:01:05
*/

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- ----------------------------
-- Table structure for tbl_book
-- ----------------------------
DROP TABLE IF EXISTS `tbl_book`;
CREATE TABLE `tbl_book` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=106 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

-- ----------------------------
-- Records of tbl_book
-- ----------------------------
BEGIN;
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (2, 'Tang Ting Fung', 'Silver', 'I may not have gone where I intended to go, but I think I have ended up where I needed to be. Navicat Data Modeler is a powerful and cost-effective database design tool which helps                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (3, 'Yokoyama Hikaru', 'Light Coral', 'I will greet this day with love in my heart. Actually it is just in an idea when feel oneself can achieve and cannot achieve.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (5, 'Lee Lai Yan', 'Jasmine', 'Navicat Data Modeler enables you to build high-quality conceptual, logical and physical data models for a wide variety of audiences. After comparing data, the window shows the number                  ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (6, 'Han Lan', 'Snow', 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your connection settings, queries, model files, and virtual group; your database passwords            ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (7, 'Wong Lai Yan', 'Sand Beige', 'A man’s best friends are his ten fingers. In other words, Navicat provides the ability for data in different databases and/or schemas to be kept up-to-date so that each repository                   ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (8, 'Xie Jialun', 'Beige', 'You can select any connections, objects or projects, and then select the corresponding buttons on the Information Pane. If the plan doesn’t work, change the plan, but never the goal.                ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (9, 'Ishii Misaki', 'Beige', 'To connect to a database or schema, simply double-click it in the pane. After comparing data, the window shows the number of records that will be inserted, updated or deleted in the target.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (10, 'Zhao Xiuying', 'Dim Gray', 'Navicat Monitor can be installed on any local computer or virtual machine and does not require any software installation on the servers being monitored. With its well-designed Graphical               ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (11, 'Yung Tin Lok', 'Yellow', 'In other words, Navicat provides the ability for data in different databases and/or schemas to be kept up-to-date so that each repository contains the same information.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (12, 'Chang Kwok Kuen', 'Vermilion', 'It collects process metrics such as CPU load, RAM usage, and a variety of other resources over SSH/SNMP. Secure SHell (SSH) is a program to log in into another computer over a network,                ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (13, 'Miu Cho Yee', 'Yellow', 'To clear or reload various internal caches, flush tables, or acquire locks, control-click your connection in the Navigation pane and select Flush and choose the flush option. You must                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (14, 'Wang Xiuying', 'Snow', 'Actually it is just in an idea when feel oneself can achieve and cannot achieve. Success consists of going from failure to failure without loss of enthusiasm. You must be the change                   ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (15, 'Watanabe Ayato', 'Apricot', 'It can also manage cloud databases such as Amazon Redshift, Amazon RDS, Alibaba Cloud. Features in Navicat are sophisticated enough to provide professional developers for all their                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (17, '测试数据123', '-----------------', '测试数据123');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (19, 'Yung Fu Shing', 'Snow', 'You will succeed because most people are lazy. I will greet this day with love in my heart. You can select any connections, objects or projects, and then select the corresponding buttons              ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (20, 'Katherine Ruiz', 'Gold', 'In the middle of winter I at last discovered that there was in me an invincible summer. Navicat Data Modeler enables you to build high-quality conceptual, logical and physical data                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (21, 'Ando Sakura', 'Persimmon', 'Navicat Cloud provides a cloud service for synchronizing connections, queries, model files and virtual group information from Navicat, other Navicat family members, different machines                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (22, 'Jia Yunxi', 'Brown', 'Navicat Cloud could not connect and access your databases. By which it means, it could only store your connection settings, queries, model files, and virtual group; your database passwords            ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (23, 'Deng Lan', 'Salmon', 'Monitored servers include MySQL, MariaDB and SQL Server, and compatible with cloud databases like Amazon RDS, Amazon Aurora, Oracle Cloud, Google Cloud and Microsoft Azure.                            ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (24, 'Pang Wai Yee', 'Indian Red', 'Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet. All the Navicat Cloud objects are located under different projects. You can share the project              ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (25, 'Yao Lan', 'Cream', 'What you get by achieving your goals is not as important as what you become by achieving your goals. Navicat Cloud provides a cloud service for synchronizing connections, queries, model               ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (26, 'Jessica Watson', 'White', 'In a Telnet session, all communications, including username and password, are transmitted in plain-text, allowing anyone to listen-in on your session and steal passwords and other information.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (27, 'Chu Wing Fat', 'Peach', 'In a Telnet session, all communications, including username and password, are transmitted in plain-text, allowing anyone to listen-in on your session and steal passwords and other information.        ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (28, 'Koyama Aoi', 'Rosy Brown', 'A man is not old until regrets take the place of dreams. You will succeed because most people are lazy. It wasn’t raining when Noah built the ark.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (29, 'Samuel Henry', 'Sepia', 'The Main Window consists of several toolbars and panes for you to work on connections, database objects and advanced tools. Secure Sockets Layer(SSL) is a protocol for transmitting                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (30, 'Kudo Aoi', 'Indian Red', 'Anyone who has ever made anything of importance was disciplined. Genius is an infinite capacity for taking pains. A comfort zone is a beautiful place, but nothing ever grows there.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (31, 'Man Wai Man', 'Maroon', 'Creativity is intelligence having fun. I destroy my enemies when I make them my friends. After logged in the Navicat Cloud feature, the Navigation pane will be divided into Navicat                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (32, 'Yamada Hikari', 'Khaki', 'Navicat Cloud provides a cloud service for synchronizing connections, queries, model files and virtual group information from Navicat, other Navicat family members, different machines                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (33, 'Ma Tin Lok', 'Tropical Orange', 'If the plan doesn’t work, change the plan, but never the goal. SSH serves to prevent such vulnerabilities and allows you to access a remote server\'s shell without compromising security.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (34, 'Florence Mendoza', 'Maroon', 'Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet. SSH serves to prevent such vulnerabilities and allows you to access a remote server\'s shell                ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (35, 'Stephanie Reed', 'Light Gray', 'Sometimes you win, sometimes you learn. Champions keep playing until they get it right. After logged in the Navicat Cloud feature, the Navigation pane will be divided into Navicat Cloud               ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (36, 'Ono Airi', 'Coffee', 'Navicat provides a wide range advanced features, such as compelling code editing capabilities, smart code-completion, SQL formatting, and more.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (37, 'Sugawara Mai', 'Indian Red', 'To get a secure connection, the first thing you need to do is to install OpenSSL Library and download Database Source. Champions keep playing until they get it right.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (38, 'Sugiyama Momoe', 'Light Gray', 'If it scares you, it might be a good thing to try. Navicat authorizes you to make connection to remote servers running on different platforms (i.e. Windows, macOS, Linux and UNIX),                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (39, 'Kimura Mai', 'Mustard', 'If the plan doesn’t work, change the plan, but never the goal. The first step is as good as half over. Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (40, 'Xia Yunxi', 'Rosy Brown', 'To successfully establish a new connection to local/remote server - no matter via SSL, SSH or HTTP, set the database login information in the General tab.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (41, 'Judy Lopez', 'Honey Orange', 'Anyone who has never made a mistake has never tried anything new. I destroy my enemies when I make them my friends. Success consists of going from failure to failure without loss of enthusiasm.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (42, 'Lau Fat', 'Misty Rose', 'The Main Window consists of several toolbars and panes for you to work on connections, database objects and advanced tools.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (43, 'Tao Yunxi', 'Iron', 'If it scares you, it might be a good thing to try. Difficult circumstances serve as a textbook of life for people. Success consists of going from failure to failure without loss of enthusiasm.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (44, 'Hirano Sara', 'Fire Brick', 'To get a secure connection, the first thing you need to do is to install OpenSSL Library and download Database Source. Navicat Monitor is a safe, simple and agentless remote server                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (45, 'Choi Sum Wing', 'Dim Gray', 'Sometimes you win, sometimes you learn. Navicat Data Modeler is a powerful and cost-effective database design tool which helps you build high-quality conceptual, logical and physical data models.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (46, 'Jerry Burns', 'Amber', 'Navicat Cloud provides a cloud service for synchronizing connections, queries, model files and virtual group information from Navicat, other Navicat family members, different machines                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (47, 'Joyce Wright', 'Misty Rose', 'Import Wizard allows you to import data to tables/collections from CSV, TXT, XML, DBF and more. Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (48, 'Ikeda Rin', 'Misty Rose', 'Secure SHell (SSH) is a program to log in into another computer over a network, execute commands on a remote server, and move files from one machine to another. Navicat authorizes you                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (49, 'Ronald Cooper', 'Brown', 'The reason why a great man is great is that he resolves to be a great man. A comfort zone is a beautiful place, but nothing ever grows there. Navicat Monitor requires a repository to                  ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (50, 'Sarah Russell', 'Black', 'A comfort zone is a beautiful place, but nothing ever grows there. You cannot save people, you can just love them. SSH serves to prevent such vulnerabilities and allows you to access                  ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (51, 'Fan Yuning', 'Light Gray', 'If it scares you, it might be a good thing to try. The Navigation pane employs tree structure which allows you to take action upon the database and their objects through their pop-up                  ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (52, 'Tanaka Aoi', 'Cream', 'You must be the change you wish to see in the world. Navicat Monitor is a safe, simple and agentless remote server monitoring tool that is packed with powerful features to make your                   ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (53, 'Noguchi Sara', 'Vermilion', 'I will greet this day with love in my heart. It is used while your ISPs do not allow direct connections, but allows establishing HTTP connections.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (54, 'Duan Xiaoming', 'Light Gray', 'What you get by achieving your goals is not as important as what you become by achieving your goals. Navicat allows you to transfer data from one database and/or schema to another with                ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (55, 'Walter Adams', 'White Smoke', 'You cannot save people, you can just love them. A man’s best friends are his ten fingers. The Main Window consists of several toolbars and panes for you to work on connections, database             ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (56, 'Siu Wai Lam', 'Olive', 'A man is not old until regrets take the place of dreams. If the Show objects under schema in navigation pane option is checked at the Preferences window, all database objects are also                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (57, 'Hung Ka Keung', 'Light Coral', 'All journeys have secret destinations of which the traveler is unaware. It is used while your ISPs do not allow direct connections, but allows establishing HTTP connections.                           ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (58, 'Ueda Mai', 'Brown', 'What you get by achieving your goals is not as important as what you become by achieving your goals. Navicat Cloud could not connect and access your databases. By which it means, it                   ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (59, 'Dong Yunxi', 'Chocolate', 'I will greet this day with love in my heart. Navicat 15 has added support for the system-wide dark mode. Navicat authorizes you to make connection to remote servers running on different               ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (60, 'Liang Yunxi', 'Light Gray', 'It is used while your ISPs do not allow direct connections, but allows establishing HTTP connections. Champions keep playing until they get it right. Navicat Data Modeler is a powerful                ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (61, 'Albert Jones', 'Chocolate', 'It collects process metrics such as CPU load, RAM usage, and a variety of other resources over SSH/SNMP. If you wait, all that happens is you get older. In other words, Navicat provides               ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (62, 'Hui Wai Man', 'Light Coral', 'Navicat authorizes you to make connection to remote servers running on different platforms (i.e. Windows, macOS, Linux and UNIX), and supports PAM and GSSAPI authentication.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (63, 'Nakajima Riku', 'Light Gray', 'After comparing data, the window shows the number of records that will be inserted, updated or deleted in the target. A comfort zone is a beautiful place, but nothing ever grows there.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (64, 'Wei Yunxi', 'Orange', 'Navicat provides powerful tools for working with queries: Query Editor for editing the query text directly, and Query Builder, Find Builder or Aggregate Builder for building queries visually.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (65, 'Wei Yunxi', 'Khaki', 'A comfort zone is a beautiful place, but nothing ever grows there. Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet. The Main Window consists                ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (66, 'Yang Rui', 'Iron', 'You will succeed because most people are lazy. Success consists of going from failure to failure without loss of enthusiasm. Actually it is just in an idea when feel oneself can achieve               ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (67, 'Jacqueline Adams', 'White Smoke', 'Creativity is intelligence having fun. The repository database can be an existing MySQL, MariaDB, PostgreSQL, SQL Server, or Amazon RDS instance.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (68, 'Nomura Yuito', 'Apricot', 'You cannot save people, you can just love them. If the Show objects under schema in navigation pane option is checked at the Preferences window, all database objects are also displayed in the pane.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (69, 'Sean Gordon', 'Beige', 'Navicat Monitor can be installed on any local computer or virtual machine and does not require any software installation on the servers being monitored. Genius is an infinite capacity                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (70, 'Ng Wing Fat', 'Fire Brick', 'The Information Pane shows the detailed object information, project activities, the DDL of database objects, object dependencies, membership of users/roles and preview.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (71, 'Yamamoto Mitsuki', 'Dark Gray', 'Actually it is just in an idea when feel oneself can achieve and cannot achieve. SQL Editor allows you to create and edit SQL text, prepare and execute selected queries.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (72, 'Mao Jiehong', 'Tangerine', 'Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (73, 'Kwok Tin Wing', 'Beige', 'It wasn’t raining when Noah built the ark. If the plan doesn’t work, change the plan, but never the goal. After logged in the Navicat Cloud feature, the Navigation pane will be                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (74, 'Iwasaki Yamato', 'Sand Beige', 'In a Telnet session, all communications, including username and password, are transmitted in plain-text, allowing anyone to listen-in on your session and steal passwords and other information.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (75, 'Nakamori Airi', 'Misty Rose', 'Secure SHell (SSH) is a program to log in into another computer over a network, execute commands on a remote server, and move files from one machine to another.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (76, 'Xiao Shihan', 'Strong Red', 'A query is used to extract data from the database in a readable format according to the user\'s request. The Information Pane shows the detailed object information, project activities,                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (77, 'Liang Zhennan', 'Strong Red', 'To get a secure connection, the first thing you need to do is to install OpenSSL Library and download Database Source.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (78, 'Lu Yunxi', 'White', 'To successfully establish a new connection to local/remote server - no matter via SSL or SSH, set the database login information in the General tab. How we spend our days is, of course,               ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (79, 'Tang Yuning', 'Peach', 'The Navigation pane employs tree structure which allows you to take action upon the database and their objects through their pop-up menus quickly and easily.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (80, 'Leung Yun Fat', 'White', 'Optimism is the one quality more associated with success and happiness than any other. All journeys have secret destinations of which the traveler is unaware. The reason why a great                   ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (81, 'Miyazaki Daisuke', 'Honey Orange', 'Anyone who has ever made anything of importance was disciplined. A query is used to extract data from the database in a readable format according to the user\'s request. The reason why                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (82, 'Huang Xiuying', 'Black', 'I will greet this day with love in my heart. Champions keep playing until they get it right. If opportunity doesn’t knock, build a door. To successfully establish a new connection                   ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (83, 'Xia Rui', 'Fire Brick', 'To successfully establish a new connection to local/remote server - no matter via SSL or SSH, set the database login information in the General tab.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (84, 'Ng Lai Yan', 'Beige', 'If the plan doesn’t work, change the plan, but never the goal. To start working with your server in Navicat, you should first establish a connection or several connections using the                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (85, 'Mao Xiaoming', 'Maroon', 'The first step is as good as half over. It can also manage cloud databases such as Amazon Redshift, Amazon RDS, Alibaba Cloud. Features in Navicat are sophisticated enough to provide                  ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (86, 'Xia Zhiyuan', 'Indian Red', 'Secure Sockets Layer(SSL) is a protocol for transmitting private documents via the Internet. The On Startup feature allows you to control what tabs appear when you launch Navicat.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (87, 'Lui Kwok Ming', 'White Smoke', 'It wasn’t raining when Noah built the ark. The Information Pane shows the detailed object information, project activities, the DDL of database objects, object dependencies, membership               ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (88, 'Kudo Mio', 'Amber', 'Instead of wondering when your next vacation is, maybe you should set up a life you don’t need to escape from. Navicat provides a wide range advanced features, such as compelling                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (89, 'Ku Ho Yin', 'Gainsboro', 'I will greet this day with love in my heart. It collects process metrics such as CPU load, RAM usage, and a variety of other resources over SSH/SNMP.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (90, 'Connie Mitchell', 'Olive', 'To connect to a database or schema, simply double-click it in the pane. HTTP Tunneling is a method for connecting to a server that uses the same protocol (http://) and the same port                   ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (91, 'Florence Allen', 'Indian Red', 'Navicat is a multi-connections Database Administration tool allowing you to connect to MySQL, Oracle, PostgreSQL, SQLite, SQL Server, MariaDB and/or MongoDB databases, making database                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (92, 'Kobayashi Shino', 'Dim Gray', 'There is no way to happiness. Happiness is the way. The Navigation pane employs tree structure which allows you to take action upon the database and their objects through their pop-up                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (93, 'Kinoshita Hikaru', 'Gainsboro', 'You cannot save people, you can just love them. Success consists of going from failure to failure without loss of enthusiasm. Difficult circumstances serve as a textbook of life for people.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (94, 'Sugiyama Riku', 'Persimmon', 'Navicat authorizes you to make connection to remote servers running on different platforms (i.e. Windows, macOS, Linux and UNIX), and supports PAM and GSSAPI authentication.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (95, 'Scott Romero', 'Dim Gray', 'To successfully establish a new connection to local/remote server - no matter via SSL or SSH, set the database login information in the General tab.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (96, 'Rebecca Ramirez', 'Orange', 'SSH serves to prevent such vulnerabilities and allows you to access a remote server\'s shell without compromising security. After comparing data, the window shows the number of records                 ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (97, 'Takada Aoshi', 'Red', 'Creativity is intelligence having fun. To start working with your server in Navicat, you should first establish a connection or several connections using the Connection window.');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (98, 'Fujiwara Minato', 'Sepia', 'To get a secure connection, the first thing you need to do is to install OpenSSL Library and download Database Source. Navicat is a multi-connections Database Administration tool allowing             ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (99, 'Ishii Aoshi', 'Red', 'Typically, it is employed as an encrypted version of Telnet. It can also manage cloud databases such as Amazon Redshift, Amazon RDS, Alibaba Cloud. Features in Navicat are sophisticated               ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (100, 'Helen Mendoza', 'Beige', 'Typically, it is employed as an encrypted version of Telnet. HTTP Tunneling is a method for connecting to a server that uses the same protocol (http://) and the same port (port 80)                    ');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (101, '测试数据123', '测试数据123', '测试数据123');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (102, '测试数据123', '测试数据123', '测试数据123');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (103, '测试数据123', '测试数据123', '测试数据123');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (104, '测试数据123', '测试数据123', '测试数据123');
INSERT INTO `tbl_book` (`id`, `name`, `type`, `description`) VALUES (105, '测试数据123', '测试数据123', '测试数据123');
COMMIT;

SET FOREIGN_KEY_CHECKS = 1;
