spring:
  data:
    mongodb:
      uri: mongodb://localhost/book
  datasource:
    url: jdbc:mysql://localhost:3306/book?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
      table-prefix: tbl_
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl